CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    email_confirmado BOOLEAN DEFAULT FALSE,
    password VARCHAR(255) NOT NULL
);