export const team_members = [
  {
    name: "Nataly Rojas",
    role: "PM / Frontend / UX",
    github: "https://github.com/natalyrojas5",
    linkedin: "https://www.linkedin.com/in/nataly-rojas",
    image: "nataly.jpeg",
    active: true,
  },
  {
    name: "Carolina Rosillo",
    role: "QA Tester / UX",
    github: "https://github.com/CarolinaRosillo",
    linkedin: "https://www.linkedin.com/in/carolinarosillog",
    image: "carolina.jpg",
    active: true,
  },
  {
    name: "Edgar Camberos",
    role: "Backend",
    github: "https://github.com/EdgarCamberos1894",
    linkedin: "https://www.linkedin.com/in/edgar-camberos-8a66052bb",
    image: "edgar.jpeg",
    active: true,
  },
  {
    name: "Samir López",
    role: "Backend",
    github: "https://github.com/lopezsDev",
    linkedin: "https://www.linkedin.com/in/samir-lopez-906437268",
    image: "samir.jpeg",
    active: true,
  },
  {
    name: "Robinson Zúñiga",
    role: "Backend",
    github: "https://github.com/robinszuniga",
    linkedin: "https://www.linkedin.com/in/robinsonzuniga",
    image: "robin.jpeg",
    active: true,
  },
  {
    name: "Conrado González",
    role: "Frontend",
    github: "https://github.com/conrado85",
    linkedin:
      "https://www.linkedin.com/in/conrado-carlos-alberto-gonzalez-3a4730b4/",
    image: "conrado.png",
    active: true,
  },
  {
    name: "Jesus Garcia",
    role: "Frontend",
    github: "https://github.com/Jesus-Garcia-Montalvo",
    linkedin: "https://www.linkedin.com/in/jesus-antonio-garcia-montalvo",
    image: "jesus.jpeg",
    active: true,
  },
  {
    name: "Jose Luis",
    role: "Frontend (No activo)",
    github: "",
    linkedin: "",
    active: false,
  },
];
